# Generated by Django 3.0.6 on 2020-05-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_profile_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('ml', 'Мужской пол'), ('fm', 'Женский пол'), ('an', 'Любой другой пол')], default='an', max_length=2),
        ),
    ]
