# Generated by Django 3.0.6 on 2020-05-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_auto_20200525_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notice',
            field=models.BooleanField(null=True),
        ),
    ]
