# Generated by Django 3.0.6 on 2020-05-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0009_auto_20200525_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notice',
            field=models.BooleanField(blank=True),
        ),
    ]
